//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bd2_teach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allow
    {
        public int Allow_id { get; set; }
        public Nullable<int> Position_prof_id { get; set; }
        public Nullable<int> Type_load_id { get; set; }
    
        public virtual Position_prof Position_prof { get; set; }
        public virtual Type_load Type_load { get; set; }
    }
}
