//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bd2_teach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prof
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prof()
        {
            this.Teaching = new HashSet<Teaching>();
        }
    
        public int Professors_id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Position_prof_id { get; set; }
    
        public virtual Position_prof Position_prof { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teaching> Teaching { get; set; }
    }
}
