//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bd2_teach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teaching
    {
        public int Teaching_id { get; set; }
        public Nullable<int> Hours_ { get; set; }
        public Nullable<int> Discipline_id { get; set; }
        public Nullable<int> Type_load_id { get; set; }
        public Nullable<int> professors_id { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Prof Prof { get; set; }
        public virtual Type_load Type_load { get; set; }
    }
}
